### ISSUE TITLE
Always Snapping to Top

### ISSUE THREAD

**Issue by donniemceduns** [justasm/DragLinearLayout#11]
Awesome library, 
i have a simple layout like this 

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        tools:context=".MainActivity">

        <com.jmedeisis.draglinearlayout.DragLinearLayout
            android:id="@+id/container"
            android:layout_width="match_parent"
            android:layout_height="match_parent" >

            <LinearLayout
                android:id="@+id/drag"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="#55000000">

                 <TextView
                     android:id="@+id/display"
                     android:layout_width="wrap_content"
                     android:layout_height="wrap_content"
                     android:text="The Quick Brown Fox Jumped!!"
                     android:padding="15dp"/>
            </LinearLayout>

        </com.jmedeisis.draglinearlayout.DragLinearLayout>

    </RelativeLayout>

The LinearLayout with id="drag" keeps snapping back to the top after i drag it. 

How do i make it maintain its new position in the layout. 

also it would be nice if there was a way to disable the snapping feature

Thanks

**Comment by justasm** [comment]
Hi, I'm sorry but DragLinearLayout was not designed for what you want to do.

Depending on the complexity, desired robustness, and time budget of what you are ultimately trying to accomplish, you could try either one of:
1. Fork this library and disable the "settle animation" in [``onDragStop``][ondragstop], which is what causes your LinearLayout to snap back to its original position. This could be tied to a configurable flag, giving you the ability to toggle the snapping feature as you wish.
2. Implement permanent offset-via-drag using your own solution, probably either calling the view's [``offsetTopAndBottom``][offsettopbottom] / ``offsetLeftAndRight`` or [``setY``][sety] / ``setX`` in response to a drag motion.

DragLinearLayout was originally intended to be used with selectively draggable items part of a linear heterogeneous list - i.e. it is designed for swapping order, not permanently offsetting its children.

Good luck and please let me know if I misunderstood your intent or need to clarify anything else.

[ondragstop]: https://github.com/justasm/DragLinearLayout/blob/91d6cc81c170e85d431b9d712db9662755a0b451/library/src/main/java/com/jmedeisis/draglinearlayout/DragLinearLayout.java#L381
[offsettopbottom]: http://developer.android.com/reference/android/view/View.html#offsetTopAndBottom(int)
[sety]: http://developer.android.com/reference/android/view/View.html#setY(float)
