### ISSUE TITLE
Why only support Vertical orientation

### ISSUE THREAD

**Issue by slmyldz** [justasm/DragLinearLayout#12]

**Comment by meesec** [comment]
check out the forks, for instance cmmcneil or my fork support both orientations.

**Comment by slmyldz** [comment]
@meesec thank you :)

**Comment by justasm** [comment]
Thanks @meesec, was going to [point to your fork as well][meesec-fork].

Hi Selim - from my personal perspective, I did not think horizontal dragging would be a common use case (see more discussion at #10). From the project's perspective, no-one contributed code that would add horizontal support.

Pull requests are always welcome :smile:

[meesec-fork]: https://github.com/meesec/DragLinearLayout
