### ISSUE TITLE
How to save new items position

### ISSUE THREAD

**Issue by peppe130** [justasm/DragLinearLayout#16]
Hi,
I have implemented your library in my App to edit buttons order in a scrollview.. It works fine but I haven't managed to save the new buttons order. Each time I restart the App, the default order is restored. Could you help me please? Thank you in advance!

**Comment by peppe130** [comment]
** My View has 9 buttons **

**Comment by justasm** [comment]
Hi!

DragLinearLayout is a widget and as such is not directly responsible for persisting the data / metadata it's displaying. So it won't be able to help you save and load your button order or the text / images they display.

Typically you will have a model of your data (in your case, this might be a List `buttonList` where each item represents the data of one of your buttons). After you initialize your UI, you can attach an `OnViewSwapListener` to DragLinearLayout to receive a callback whenever the user swaps any two items. Inside this callback you can swap the item order in your model, e.g.
```java
dragLinearLayout.setOnViewSwapListener(new DragLinearLayout.OnViewSwapListener() {
    @Override
    public void onSwap(View firstView, int firstPosition,
            View secondView, int secondPosition) {
        Collections.swap(buttonList, firstPosition, secondPosition);
    }
});
```
Take a look at the [sample NoteActivity][sample-note-activity] for a full example of this.

This will keep your data model up-to-date while your app is running, but on every restart this order will still be lost. To prevent this you will need to persist your data model in device storage using one of multiple techniques available in Android, of which a good overview can be found in [the official documentation][storage-docs]. Once you have implemented a solution that fits your requirements, every time the app is launched anew / restarted, load your data model from storage and populate DragLinearLayout accordingly.

[sample-note-activity]: https://github.com/justasm/DragLinearLayout/blob/cc1a250a0d98278662e473bf4f3660d06bcbc708/sample/src/main/java/com/jmedeisis/example/draglinearlayout/NoteActivity.java
[storage-docs]: http://developer.android.com/guide/topics/data/data-storage.html
