### ISSUE TITLE
Get the Child position 

### ISSUE THREAD

**Issue by alexiscanny** [justasm/DragLinearLayout#19]
Hi there,
I wonder say first of all thank you for your amazing job, is really useful.
My issue is about, how can I get the child position after drag and drop few times the picture inside the container (Custom View)?

I need to passing the uri of each image after the user have swapped all the pics to another activity, but I couldn't find a solution.

Could you help me please.

Thanks for you help

**Comment by justasm** [comment]
Typically you will have a model of your data (in your case, this might be a List `imageList` where each item is the corresponding image's URI). After you initialize your UI, you can attach an `OnViewSwapListener` to DragLinearLayout to receive a callback whenever the user swaps any two items. Inside this callback you can swap the item order in your model, e.g.
```java
dragLinearLayout.setOnViewSwapListener(new DragLinearLayout.OnViewSwapListener() {
    @Override
    public void onSwap(View firstView, int firstPosition,
            View secondView, int secondPosition) {
        Collections.swap(imageList, firstPosition, secondPosition);
    }
});
```
Take a look at the [sample NoteActivity][sample-note-activity] for an example (although note that for simplicity it does not have an explicit dynamic data model, and thus doesn't update one in the callback).

Once it is time to navigate to another Activity, you can attach a copy of your latest model to the Intent used to start it, e.g. by converting the URIs to Strings and [adding them as an extra][intent-put-extra-arraylist-string]. In your new Activity you can call [`getIntent()`][get-intent] and retrieve your list of URIs.

[sample-note-activity]: https://github.com/justasm/DragLinearLayout/blob/cc1a250a0d98278662e473bf4f3660d06bcbc708/sample/src/main/java/com/jmedeisis/example/draglinearlayout/NoteActivity.java
[intent-put-extra-arraylist-string]: http://developer.android.com/reference/android/content/Intent.html#putStringArrayListExtra(java.lang.String,%20java.util.ArrayList<java.lang.String>)
[get-intent]: http://developer.android.com/reference/android/app/Activity.html#getIntent()

**Comment by alexiscanny** [comment]
Hi Justasm, 
I really appreciate the effort you put to explain to me that. I did all the changes today and I created an `Hashmap <Integer, Uri> mapuri = new HashMap<Integer, Uri>();` where I'm able to add the picture before the swap. 
e.g. 
Position Index Uri
0              0       uriChild0
1              1       uriChild1
2              2       uriChild2

At this point I'm changing the container and became:
Child2
Child1
Child0

So now how I can know if there are changes into the container and if yes which child now is in the position 0, or in the position 1, or in the position 2?

Because what I want to do is, 
String firstUriChoose is: uriChild2
String secondUriChoose is: uriChild1
String thirdUriChoose is: uriChild0

But how I can see the changes inside my container? how I know that the child that was in third position is now the first?
Even when I do:
`String newFirstUri = mapuri.get(getChildIndex(mSelectedImagesContainer.getChildAt(0))).toString();`
doesn't give me the right Uri.

Thanks for any helps you can give to me.

**Comment by justasm** [comment]
How about:
```java
List<Uri> imageList = new ArrayList<>();
imageList.add(uriChild0);
imageList.add(uriChild1);
imageList.add(uriChild2);

dragLinearLayout.setOnViewSwapListener(new DragLinearLayout.OnViewSwapListener() {
    @Override
    public void onSwap(View firstView, int firstPosition,
            View secondView, int secondPosition) {
        Collections.swap(imageList, firstPosition, secondPosition);
    }
});
```
After swapping Child0 with Child2, you can check
```java
Uri newFirstUri = imageList.get(0);
```
which will be `uriChild2`.

**Comment by alexiscanny** [comment]
Great man, I did other changes but always following your way.. Amazing, thank u for everything and if u are in London let me know it will be a pleasure offer u a beer  ;))
