### ISSUE TITLE
Are you planning to support horizontal orientation?

### ISSUE THREAD

**Issue by sakura1219** [justasm/DragLinearLayout#20]
First, I appreciate your library. This is working like a charm.
However, I want to use this library to horizontal orientation.
Are you planning to support horizontal orientation in the near future?
Or, I would try it by myself. Then, could you give me some tips for that? (like if there is a big problem to do that, please let me know so that I could save some time)

**Comment by justasm** [comment]
Hey,

The issue regarding horizontal orientation has been brought up and discussed previously in #12 and #10. In short, I do not plan to personally add horizontal support, although I would be open to reviewing a pull request from @cmcneil or @meesec 's forks. In any case, feel welcome to review tips at the aforementioned issues and / or use one of the forked projects.

You may also be interested in considering an alternative official, modern, well-documented and extensible approach using a [`RecyclerView`][recyclerview] with [`ItemTouchHelper`][item-touch-helper] to provide drag and drop support. You can [find a good overview and tutorial here][drag-swipe-recyclerview-tut].

[recyclerview]: http://developer.android.com/training/material/lists-cards.html#RecyclerView
[item-touch-helper]: https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.html
[drag-swipe-recyclerview-tut]: https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf
