### ISSUE TITLE
Is it possible to disable overdragg?

### ISSUE THREAD

**Issue by Dwite** [justasm/DragLinearLayout#24]
To prevent from being dragger under DragLinearLayout edges.

**Comment by justasm** [comment]
It would be possible to do by modifying the logic inside `DragLinearLayout`'s [`onDrag()`](https://github.com/justasm/DragLinearLayout/blob/548332de49631af7db61e3a44ee6a572f39f0f57/library/src/main/java/com/jmedeisis/draglinearlayout/DragLinearLayout.java#L430) method.

Pull requests are welcome :smile:

**Comment by broakenmedia** [comment]
If anyone reads this in future, i managed to get this working. It's by NO MEANS perfect but just about gets the job done for now.

In the "onTouchEvent" -> "ACTION_MOVE"

simply place this at the bottom:

    if(lastEventY >= (getHeight() - (draggedItem.height / 2)) || lastEventY <= ((draggedItem.height / 2))){
        return false;
    }
