### ISSUE TITLE
custom onDragStopListener

### ISSUE THREAD

**Issue by vanlooverenkoen** [justasm/DragLinearLayout#30]
Is there a way to get a onDragStopListener?
I need to detect when the view is placed in the right position?
because if I use setOnViewSwapListener(); the order of the views in the draglinearlayout is not committed.

if someone changes the order of the views. I need to read the correct order of the views so I can handle code for each view.

view1.print("1");
view2.print("2");
view3.print("3");

after changing the order 2 becomes 3 and 3 becomes 2. this is what I need to call

view1.print("1");
view3.print("3");
view2.print("2");

How can I do this?

**Comment by vanlooverenkoen** [comment]
```
    mDragLayout.setOnTouchListener(new View.OnTouchListener() {
        @Override
        public boolean onTouch(View view, MotionEvent motionEvent) {
            if (MotionEventCompat.getActionMasked(motionEvent) == MotionEvent.ACTION_UP) {
                updatePreviewsCallback.executeCallback();
            }
            return false;
        }
    });
```

this is what I found that worked, but maybe you could implement it in the api to add a dedecated listener. just a suggestion

**Comment by justasm** [comment]
Hey!

The order _is_ in fact committed when the `onSwap` callback is called, so it would be the proper place to update your model. Thanks for the suggestion and for posting your solution.

**Comment by vanlooverenkoen** [comment]
onSwap? is this a public API? I can't find it
or do you mean the: OnViewSwapListener?

because at that point if you loop over all your views they are still in the previous position only if you let go of the draghandler the position will be changed

**Comment by justasm** [comment]
I did mean the `OnViewSwapListener`.
You are correct that the View positions are swapped only after the callback is invoked, which in retrospect is probably not the expected behaviour. However, you have sufficient information with the initial state and the sequence of `onSwap` callbacks to know at any time what the current order is.

If you need to specifically detect ACTION_UP, the solution you provided is one correct way to do it.

**Comment by vanlooverenkoen** [comment]
yes indeed, thanks again for your awesome lib
