### ISSUE TITLE
Support drag and drop  Listview or child View's  elements

### ISSUE THREAD

**Issue by Bekakk** [justasm/DragLinearLayout#35]
Hi
I'm using your library.Everything  working perfect,but i have one question.Is it a possible to use this librare in Listview,I mean BaseAdapter, or if i add childView programmatically?
I tried SimpleAdapter and BaseAdapter,but   i still can't drag and drop in listviews.
thanks

**Comment by justasm** [comment]
No, it was not designed for this use case.

I'd suggest to consider using a [`RecyclerView`](http://developer.android.com/training/material/lists-cards.html#RecyclerView) with [`ItemTouchHelper`](https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.html) to provide drag and drop support. You can [find a good overview and tutorial here](https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf).

**Comment by Bekakk** [comment]
Thanks Justas your attention
