### ISSUE TITLE
Make switchViewStartTop switchViewStartY

### ISSUE THREAD

**Issue by DreaminginCodeZH** [justasm/DragLinearLayout#4]
First thank you for making this library open source, it really helped me a lot when implementing the animation when using native drag and drop API.

And I've found a small issue when reading the code in this library. On [DragLinearLayout.java#L424](https://github.com/justasm/DragLinearLayout/blob/master/library/src/main/java/com/jmedeisis/draglinearlayout/DragLinearLayout.java#L424), if switch view is being animated, the visual position will be View.getY() instead of View.getTop(), and using getY() can avoid the visual glitch that happens when the switch view is going back and forth midway in the animation. You can observe this behavior if you make the animation time larger, for example 1 second, and drag the item around another view up and down quickly.

**Comment by justasm** [comment]
Glad it has been of help! Good catch, thanks for the detailed issue.
