### ISSUE TITLE
Retrofit2 incompatibility on Android 5.x

### ISSUE THREAD

**Issue by diergui** [justasm/DragLinearLayout#42]
When I add compile 'com.jmedeisis:draglinearlayout:1.1.0' to Gradle and I run the App on Android 5 device, the app crash when try to load Retrofit2 (compile 'com.squareup.retrofit2:retrofit:2.3.0' AND compile 'com.squareup.retrofit2:converter-gson:2.3.0'). With Android 6 o + the Apps aren't crashing.

**Comment by justasm** [comment]
Sorry, but it is not possible that this library is not compatible with Retrofit as it is purely a UI component and does not attempt in any way to integrate with networking libraries. When reporting crashes please always share the stack trace.
