### ISSUE TITLE
Support drag&drop item (child of DragLinearLayout)  between multiple draglinearlayouts? 

### ISSUE THREAD

**Issue by thanhvn-15** [justasm/DragLinearLayout#43]

**Comment by justasm** [comment]
Hi, it's unlikely that `DragLinearLayout` will support what you want. It was built from the ground up as a `ViewGroup` that only manages its immediate child views.

You may want to take a look at the [platform drag & drop APIs](https://developer.android.com/guide/topics/ui/drag-drop.html).

If you have any specific ideas or topics of discussion, feel free to reopen this issue.
