### ISSUE TITLE
Unable to resolve depenency

### ISSUE THREAD

**Issue by carlos-mg89** [justasm/DragLinearLayout#45]
Hi!

Your implementation seams to be quite simple to put in place and I'd love to give it a try. However, even though I have jcenter in my project's build.gradle, and after adding `compile 'com.jmedeisis:draglinearlayout:1.1.0'` into my app's build.gradle, I get the following error:

`Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.jmedeisis:draglinearlayout:1.1.0`

Actually, I get many **Unable to resolve dependency for** errors while trying to sync my build.gradle

Has it been changed from jcenter and now uses another repository? I have the google one added as well.

**Comment by justasm** [comment]
Hi, nothing in the repo has changed, so it is likely that there may be some issue with your configuration. Please make sure you have disabled Gradle's offline mode. To help you further we'd need more info, such as your full Gradle configuration, which version of the Gradle plugin you're using, and any other relevant information.

**Comment by carlos-mg89** [comment]
Thanks! I just enabled the Gradle's offline mode an hour ago and forgot to turn it off.

Now I'm going to play a little bit with the DragLinearLayout 👍

**Comment by carlos-mg89** [comment]
@justasm well, actually it works really well! Congratulations for writing a simple but highly effective and reusable component.
