### ISSUE TITLE
programmatically swap children

### ISSUE THREAD

**Issue by AnassHmida** [justasm/DragLinearLayout#46]
Can you help me deal with swapping children programmatically ? the only solution i can find is to delete a view and add it to a position , but it's not a clean  solution , i want it to be animated just like a simple drag animation.

**Comment by justasm** [comment]
This library was not designed to support animation for such use cases.

I'd suggest to consider using a [`RecyclerView`](http://developer.android.com/training/material/lists-cards.html#RecyclerView) with [`ItemTouchHelper`](https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.html) to provide drag and drop support. You can [find a good overview and tutorial here](https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf).

`RecyclerView` supports animations on programmatic data changes out-of-the-box.
