### ISSUE TITLE
Can i get all added child position after swap and drag ?

### ISSUE THREAD

**Issue by GauravCreed** [justasm/DragLinearLayout#49]
Hi @justasm 

it's a great work you have done, Thanks You.

I have added 4 ImageView in DragLinearLayout then after add setViewDraggable and also set setOnViewSwapListener in my App

My question is when i drag and swipe child view can i get Last Changed position  with tag?

Thanks.

**Comment by gelldur** [comment]
Hello, I'm not sure I'm correct person to ask about this ;) I don't actively develop any longer in Android.

**Comment by GauravCreed** [comment]
Hi @gelldur 

Will u pls tell me to which person to tag for this issue 

Thanks.

**Comment by justasm** [comment]
Hey, check out the included sample
https://github.com/justasm/DragLinearLayout/blob/2d4bcfab79ef17aa72a5c77cebf5456e8b521b87/sample/src/main/java/com/jmedeisis/example/draglinearlayout/NoteActivity.java#L48

You can keep track of the index / position / other data by setting a tag yourself in the `OnViewSwapListener` callback.
