### ISSUE TITLE
very hard to implement custom drag view (addDragView)

### ISSUE THREAD

**Issue by azizimusa** [justasm/DragLinearLayout#5]
Can you show some sample that doesn't inflate new layout? just using current layout, and pick some ID to allow draggable.

**Comment by justasm** [comment]
Have you tried using setViewDraggable(View, View) as [here in the sample](https://github.com/justasm/DragLinearLayout/blob/be3850633b/sample/src/main/java/com/jmedeisis/example/draglinearlayout/DemoActivity.java#L21)? If you pass in a previously inflated child of the DragLinearLayout, this will make it draggable. If you need a reference to the child by ID, you can use findViewById().

If this isn't helpful, could you please clarify what sort of behavior you expect and what happens instead?

**Comment by azizimusa** [comment]
Hi, thanks for the suggestion. It solved my problem :)

**Comment by justasm** [comment]
Great!
