### ISSUE TITLE
Any idea how to save the layout as after dragging ?

### ISSUE THREAD

**Issue by azizimusa** [justasm/DragLinearLayout#6]
Hi,

I want to load the layout (after drag) even after user has restarted his phone. Is this possible?

**Comment by justasm** [comment]
Yes, it's possible!

If you look at the [notes sample](https://github.com/justasm/DragLinearLayout/blob/be3850633b/sample/src/main/java/com/jmedeisis/example/draglinearlayout/NoteActivity.java) it is doing almost what you want. It [loads and adds](https://github.com/justasm/DragLinearLayout/blob/be3850633b/sample/src/main/java/com/jmedeisis/example/draglinearlayout/NoteActivity.java#L39) previously saved notes (in the sample's case these are static as they are loaded from resources). It then [uses an OnViewSwapListener](https://github.com/justasm/DragLinearLayout/blob/be3850633b/sample/src/main/java/com/jmedeisis/example/draglinearlayout/NoteActivity.java#L43) to keep track of changes to the layout; here you should update your backing data, which you could subsequently store to disk in the Activity's onPause, for example. On next Activity start you could load this data from disk and populate your layout dynamically as above.

However, as this is a UI library you will have to do some legwork to implement the data storage yourself. You can use any persistence solution that suits your experience and needs, e.g. SQLite, Realm, or even SharedPreferences.
